---
title: "Covid Preditora"
author: "Raianny"
date: "01/05/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message=FALSE,
                      warning=FALSE,
                      cache = TRUE,
                      dev = "png",
                      dpi = 500)
```

```{r}
#Pacotes
library(lubridate)
library(tidyverse)
library(tidymodels)
library(usemodels)
library(GGally)
library(vip)
```

# Resumo dos Modelos

\begin{center}
\begin{tabular}{l c c c c c c}
\hline
K & RMSE (treino) & RSQ (treino) & RMSE final (treino) & RSQ (treino) & RMSE final (teste) & RSQ (teste)\\
\hline
1 & $15662$ & $0.040$ & $13959$ & $0.695$ & $4485$ & $0.234$ \\
2 & $19326$ & $0.039$ & $17410$ & $0.525$ & $8310$ & $0.176$ \\
3 & $20224$ & $0.043$ & $18254$ & $0.478$ & $9267$ & $0.126$ \\
4 & $20158$ & $0.042$ & $18207$ & $0.481$ & $8810$ & $0.219$ \\
5 & $19619$ & $0.038$ & $17484$ & $0.521$ & $8805$ & $0.131$ \\
6 & $16116$ & $0.035$ & $14930$ & $0.648$ & $11895$ & $0.101$ \\
7 & $11039$ & $0.050$ & $9494$ & $0.858$ & $2528$ & $0.959$ \\
8 & $16075$ & $0.034$ & $14916$ & $0.648$ & $6823$ & $0.114$ \\
9 & $19646$ & $0.029$ & $17830$ & $0.497$ & $9624$ & $0.193$ \\
10 & $20603$ & $0.025$ & $18664$ & $0.449$ & $10556$ & $0.120$ \\
11 & $20700$ & $0.035$ & $17789$ & $0.502$ & $11625$ & $0.221$ \\
12 & $19765$ & $0.035$ & $18080$ & $0.481$ & $10996$ & $0.104$ \\
13 & $16864$ & $0.033$ & $15537$ & $0.615$ & $12239$ & $0.248$ \\
14 & $12846$ & $0.042$ & $11732$ & $0.780$ & $3210$ & $0.958$ \\

\hline
\end{tabular}
\end{center}

Melhores modelos com $k=7$ e $k=14$.

# Modelos

```{r}
#Dados do covid
covid <- read.csv('dados_covid.csv') %>% 
         mutate(dias = 1:length(covid)) 
```

```{r}

for(k in 1:5) {
  covid_k <- lag(covid, n=k) %>% 
             mutate(dias=1:653) %>% 
             na.omit() %>% 
             select(-date)
  
  
  atraso <- full_join(covid, covid_k , by = 'dias') %>% 
    select(-dias, -date) %>% 
    na.omit()
  
  names(atraso) <- c('covid', 'covid_atraso')
  
  
  set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion")
  
  #Separação dos dados entre treino e teste 
  
  #Utilizando apenas 7 dias para o teste
  atraso_split <- initial_time_split(atraso, strata = covid, prop = .9893)
  atraso_train <- training(atraso_split)
  atraso_test <- testing(atraso_split)
  
  set.seed(234, kind = "Mersenne-Twister", normal.kind = "Inversion")
  
  #Fazendo os folds
  atraso_folds <- vfold_cv(atraso_train, v = 5, strata = covid)
  atraso_folds

  #Modelo
  ranger_recipe <-
    recipe(formula = covid ~ ., data = atraso_train) 
  
  ranger_spec <-
    rand_forest(mtry = tune(), min_n = tune(), trees = tune()) %>%
    set_mode("regression") %>%
    set_engine("ranger")
  
  #grid de procura
  atraso_grid <- grid_regular(mtry(range(1, 5)),
                              trees(range(500, 1000)),
                              min_n(range(10, 100)),
                              levels = c(2, 3, 10))
  ranger_workflow <-
    workflow() %>%
    add_recipe(ranger_recipe) %>%
    add_model(ranger_spec)
  
  set.seed(8577, kind = "Mersenne-Twister", normal.kind = "Inversion")
  doParallel::registerDoParallel()
  ranger_tune <-
    tune_grid(ranger_workflow,
              resamples = atraso_folds,
              grid = atraso_grid
    )
  
  print(paste("Modelo com k =", k))
  
  print(show_best(ranger_tune, metric = "rmse"))
  
  print(show_best(ranger_tune, metric = "rsq"))
  
  print(autoplot(ranger_tune))
  
  final_rf <- ranger_workflow %>%
  finalize_workflow(select_best(ranger_tune))

  final_rf

  #A função last_fit() ajusta essa floresta aleatória finalizada 
  #uma última vez aos dados de treinamento e avalia uma última 
  #vez nos dados de teste.

  dados_fit<- last_fit(final_rf, atraso_split)
  dados_fit

  print(collect_metrics(dados_fit))
  
  modelo <- predict(dados_fit$.workflow[[1]],atraso_train) %>% 
            mutate(dias= 1:(646-k))
  atraso <- atraso_train %>% 
            mutate(dias= 1:(646-k))
  
  geral <- full_join(modelo, atraso, by = 'dias')
  
  print(ggplot(geral, aes(covid, .pred))+
        geom_abline(lty = 2, color = "gray50") +
        geom_point(alpha = 0.5, color = "midnightblue"))
  
  print(ggplot(geral)+
        geom_line(aes(x = dias, y = covid, color = "Observado"))+
        geom_line(aes(x = dias, y = .pred, color = "Predito"))+
        scale_colour_manual(values = c("midnightblue", "yellow"))+
        labs(title= paste("Modelo para os dados de treino com k =", k),
             y="Número de casos"))
      
  modelo_k <- predict(dados_fit$.workflow[[1]], atraso_test) %>% 
                    mutate(dias= 1:7)
  atraso_k<- atraso_test %>% 
             mutate(dias= 1:7)

  geral_teste <- full_join(modelo_k, atraso_k, by = 'dias')

  print(ggplot(geral_teste)+
        geom_line(aes(x = dias, y = covid, color = "Observado"))+
        geom_line(aes(x = dias, y = .pred, color = "Predito"))+
        scale_colour_manual(values = c("midnightblue", "yellow"))+
        labs(title= paste("Modelo para os dados de teste com k =", k),
             y="Número de casos"))
 
  #Métricas para os dados de treino
  
  print(paste("Métricas para os dados de treino com k =", k))
  
  resultado_dados_fit <-
    atraso_train %>%
    bind_cols(predict(dados_fit$.workflow[[1]], atraso_train) %>%
                rename(predicao_dados_fit= .pred))


  print(metrics(resultado_dados_fit,
                truth = covid,
                estimate = predicao_dados_fit,
                options = "rmse"))
  
  #Métricas para os dados de teste 
  
  print(paste("Métricas para os dados de teste com k =", k))
  
  resultado_dados_fit <-
    atraso_test %>%
    bind_cols(predict(dados_fit$.workflow[[1]], atraso_test) %>%
                rename(predicao_dados_fit= .pred))
  
  
  print(metrics(resultado_dados_fit,
                truth = covid,
                estimate = predicao_dados_fit,
                options = "rmse"))
  
}

```

```{r}

for(k in 6:10) {
    covid_k <- lag(covid, n=k) %>% 
             mutate(dias=1:653) %>% 
             na.omit() %>% 
             select(-date)
  
  
  atraso <- full_join(covid, covid_k , by = 'dias') %>% 
    select(-dias, -date) %>% 
    na.omit()
  
  names(atraso) <- c('covid', 'covid_atraso')
  
  
  set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion")  
  
  #Separação dos dados entre treino e teste 
  
  #Utilizando apenas 7 dias para o teste
  atraso_split <- initial_time_split(atraso, strata = covid, prop = .9893)
  atraso_train <- training(atraso_split)
  atraso_test <- testing(atraso_split)
  
  set.seed(234, kind = "Mersenne-Twister", normal.kind = "Inversion")
  
  #Fazendo os folds
  atraso_folds <- vfold_cv(atraso_train, v = 5, strata = covid)
  atraso_folds

  #Modelo
  ranger_recipe <-
    recipe(formula = covid ~ ., data = atraso_train) 
  
  ranger_spec <-
    rand_forest(mtry = tune(), min_n = tune(), trees = tune()) %>%
    set_mode("regression") %>%
    set_engine("ranger")
  
  #grid de procura
  atraso_grid <- grid_regular(mtry(range(1, 5)),
                              trees(range(500, 1000)),
                              min_n(range(10, 100)),
                              levels = c(2, 3, 10))
  ranger_workflow <-
    workflow() %>%
    add_recipe(ranger_recipe) %>%
    add_model(ranger_spec)
  
  set.seed(8577, kind = "Mersenne-Twister", normal.kind = "Inversion")
  doParallel::registerDoParallel()
  ranger_tune <-
    tune_grid(ranger_workflow,
              resamples = atraso_folds,
              grid = atraso_grid
    )
  
  print(paste("Modelo com k =", k))
  
  print(show_best(ranger_tune, metric = "rmse"))
  
  print(show_best(ranger_tune, metric = "rsq"))
  
  print(autoplot(ranger_tune))
  
  final_rf <- ranger_workflow %>%
  finalize_workflow(select_best(ranger_tune))

  final_rf

  #A função last_fit() ajusta essa floresta aleatória finalizada 
  #uma última vez aos dados de treinamento e avalia uma última 
  #vez nos dados de teste.

  dados_fit<- last_fit(final_rf, atraso_split)
  dados_fit

  print(collect_metrics(dados_fit))
  
  modelo <- predict(dados_fit$.workflow[[1]],atraso_train) %>% 
            mutate(dias= 1:(646-k))
  atraso <- atraso_train %>% 
            mutate(dias= 1:(646-k))
  
  geral <- full_join(modelo, atraso, by = 'dias')
  
  print(ggplot(geral, aes(covid, .pred))+
        geom_abline(lty = 2, color = "gray50") +
        geom_point(alpha = 0.5, color = "midnightblue"))
  
  print(ggplot(geral)+
        geom_line(aes(x = dias, y = covid, color = "Observado"))+
        geom_line(aes(x = dias, y = .pred, color = "Predito"))+
        scale_colour_manual(values = c("midnightblue", "yellow"))+
        labs(title= paste("Modelo para os dados de treino com k =", k),
             y="Número de casos"))
      
  modelo_k <- predict(dados_fit$.workflow[[1]], atraso_test) %>% 
                    mutate(dias= 1:7)
  atraso_k<- atraso_test %>% 
             mutate(dias= 1:7)

  geral_teste <- full_join(modelo_k, atraso_k, by = 'dias')

  print(ggplot(geral_teste)+
        geom_line(aes(x = dias, y = covid, color = "Observado"))+
        geom_line(aes(x = dias, y = .pred, color = "Predito"))+
        scale_colour_manual(values = c("midnightblue", "yellow"))+
        labs(title= paste("Modelo para os dados de teste com k =", k),
             y="Número de casos"))
 
  #Métricas para os dados de treino
  
  print(paste("Métricas para os dados de treino com k =", k))
  
  resultado_dados_fit <-
    atraso_train %>%
    bind_cols(predict(dados_fit$.workflow[[1]], atraso_train) %>%
                rename(predicao_dados_fit= .pred))


  print(metrics(resultado_dados_fit,
                truth = covid,
                estimate = predicao_dados_fit,
                options = "rmse"))
  
  #Métricas para os dados de teste 
  
  print(paste("Métricas para os dados de teste com k =", k))
  
  resultado_dados_fit <-
    atraso_test %>%
    bind_cols(predict(dados_fit$.workflow[[1]], atraso_test) %>%
                rename(predicao_dados_fit= .pred))
  
  
  print(metrics(resultado_dados_fit,
                truth = covid,
                estimate = predicao_dados_fit,
                options = "rmse"))
  
}

```

```{r}

for(k in 11:14) {
    covid_k <- lag(covid, n=k) %>% 
             mutate(dias=1:653) %>% 
             na.omit() %>% 
             select(-date)
  
  
  atraso <- full_join(covid, covid_k , by = 'dias') %>% 
    select(-dias, -date) %>% 
    na.omit()
  
  names(atraso) <- c('covid', 'covid_atraso')
  
  
  set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion")
  
  #Separação dos dados entre treino e teste 
  
  #Utilizando apenas 7 dias para o teste
  atraso_split <- initial_time_split(atraso, strata = covid, prop = .9893)
  atraso_train <- training(atraso_split)
  atraso_test <- testing(atraso_split)
  
  set.seed(234, kind = "Mersenne-Twister", normal.kind = "Inversion")
  
  #Fazendo os folds
  atraso_folds <- vfold_cv(atraso_train, v = 5, strata = covid)
  atraso_folds

  #Modelo
  ranger_recipe <-
    recipe(formula = covid ~ ., data = atraso_train) 
  
  ranger_spec <-
    rand_forest(mtry = tune(), min_n = tune(), trees = tune()) %>%
    set_mode("regression") %>%
    set_engine("ranger")
  
  #grid de procura
  atraso_grid <- grid_regular(mtry(range(1, 5)),
                              trees(range(500, 1000)),
                              min_n(range(10, 100)),
                              levels = c(2, 3, 10))
  ranger_workflow <-
    workflow() %>%
    add_recipe(ranger_recipe) %>%
    add_model(ranger_spec)
  
  set.seed(8577, kind = "Mersenne-Twister", normal.kind = "Inversion")
  doParallel::registerDoParallel()
  ranger_tune <-
    tune_grid(ranger_workflow,
              resamples = atraso_folds,
              grid = atraso_grid
    )
  
  print(paste("Modelo com k =", k))
  
  print(show_best(ranger_tune, metric = "rmse"))
  
  print(show_best(ranger_tune, metric = "rsq"))
  
  print(autoplot(ranger_tune))
  
  final_rf <- ranger_workflow %>%
  finalize_workflow(select_best(ranger_tune))

  final_rf

  #A função last_fit() ajusta essa floresta aleatória finalizada 
  #uma última vez aos dados de treinamento e avalia uma última 
  #vez nos dados de teste.

  dados_fit<- last_fit(final_rf, atraso_split)
  dados_fit

  print(collect_metrics(dados_fit))
  
  modelo <- predict(dados_fit$.workflow[[1]],atraso_train) %>% 
            mutate(dias= 1:(646-k))
  atraso <- atraso_train %>% 
            mutate(dias= 1:(646-k))
  
  geral <- full_join(modelo, atraso, by = 'dias')
  
  print(ggplot(geral, aes(covid, .pred))+
        geom_abline(lty = 2, color = "gray50") +
        geom_point(alpha = 0.5, color = "midnightblue"))
  
  print(ggplot(geral)+
        geom_line(aes(x = dias, y = covid, color = "Observado"))+
        geom_line(aes(x = dias, y = .pred, color = "Predito"))+
        scale_colour_manual(values = c("midnightblue", "yellow"))+
        labs(title= paste("Modelo para os dados de treino com k =", k),
             y="Número de casos"))
      
  modelo_k <- predict(dados_fit$.workflow[[1]], atraso_test) %>% 
                    mutate(dias= 1:7)
  atraso_k<- atraso_test %>% 
             mutate(dias= 1:7)

  geral_teste <- full_join(modelo_k, atraso_k, by = 'dias')

  print(ggplot(geral_teste)+
        geom_line(aes(x = dias, y = covid, color = "Observado"))+
        geom_line(aes(x = dias, y = .pred, color = "Predito"))+
        scale_colour_manual(values = c("midnightblue", "yellow"))+
        labs(title= paste("Modelo para os dados de teste com k =", k),
             y="Número de casos"))
 
  #Métricas para os dados de treino
  
  print(paste("Métricas para os dados de treino com k =", k))
  
  resultado_dados_fit <-
    atraso_train %>%
    bind_cols(predict(dados_fit$.workflow[[1]], atraso_train) %>%
                rename(predicao_dados_fit= .pred))


  print(metrics(resultado_dados_fit,
                truth = covid,
                estimate = predicao_dados_fit,
                options = "rmse"))
  
  #Métricas para os dados de teste 
  
  print(paste("Métricas para os dados de teste com k =", k))
  
  resultado_dados_fit <-
    atraso_test %>%
    bind_cols(predict(dados_fit$.workflow[[1]], atraso_test) %>%
                rename(predicao_dados_fit= .pred))
  
  
  print(metrics(resultado_dados_fit,
                truth = covid,
                estimate = predicao_dados_fit,
                options = "rmse"))
}

```
