---
title: "Modelagem final"
author: "Raianny"
date: "23/05/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message=FALSE,
                      warning=FALSE,
                      cache = TRUE,
                      dev = "png",
                      dpi = 500)
```

**Modelo com apenas a váriavel covid atrasada em 7 dias.**

```{r}

#Pacotes
library(covid19br)
library(lubridate)
library(tidyverse)
library(tidymodels)
library(usemodels)
library(vip)

```

# Coleta dos dados

```{r}

covid <- downloadCovid19("brazil") %>% 
  select(date, newCases) %>% 
  filter(date < date('2021-12-10'), date > date('2020-02-25')) %>% 
  mutate(dias = 1:653) 

names(covid) <- c('date','covid','dias')

```

# Engenharia de Variável

```{r}

covid_k <- lag(covid, n=7) %>% 
  mutate(dias=1:653) %>% 
  na.omit() %>% 
  select(-date)
  
  
atraso <- full_join(covid, covid_k , by = 'dias') %>% 
  select(-dias, -date) %>% 
  na.omit()

names(atraso) <- c('covid', 'covid_atraso')

```

# Modelagem Inicial

```{r}
set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion")

#Separação dos dados entre treino e teste 

#Utilizando apenas 7 dias para o teste
atraso_split <- initial_time_split(atraso, strata = covid, prop = .9893)
atraso_train <- training(atraso_split)
atraso_test <- testing(atraso_split)

set.seed(234, kind = "Mersenne-Twister", normal.kind = "Inversion")

#Fazendo os folds
atraso_folds <- vfold_cv(atraso_train, v = 5, strata = covid)
atraso_folds

#Modelo
ranger_recipe <-
  recipe(formula = covid ~ ., data = atraso_train) 

ranger_spec <-
  rand_forest(mtry = tune(), min_n = tune(), trees = tune()) %>%
  set_mode("regression") %>%
  set_engine("ranger")

#grid de procura
atraso_grid <- grid_regular(mtry(range(1, 5)),
                            trees(range(500, 1000)),
                            min_n(range(10, 100)),
                            levels = c(5, 3, 10))
ranger_workflow <-
  workflow() %>%
  add_recipe(ranger_recipe) %>%
  add_model(ranger_spec)

set.seed(8577, kind = "Mersenne-Twister", normal.kind = "Inversion")
doParallel::registerDoParallel()
ranger_tune <-
  tune_grid(ranger_workflow,
            resamples = atraso_folds,
            grid = atraso_grid
  )

```

# Métricas 

```{r}

print(show_best(ranger_tune, metric = "rmse"))

print(show_best(ranger_tune, metric = "rsq"))

print(autoplot(ranger_tune) +
      scale_colour_manual(values = c("#3299CC", 
                                      "yellow", "midnightblue","#CC3399", "#CCCCFF"))+
      labs(title= "Comportamento entre os parâmetros",
       x="Níveis",
       colour="Preditores"
       )+
      theme_minimal())

```

# Modelagem Final

```{r}
final_rf <- ranger_workflow %>%
  finalize_workflow(select_best(ranger_tune))

final_rf

#A função last_fit() ajusta essa floresta aleatória finalizada 
#uma última vez aos dados de treinamento e avalia uma última 
#vez nos dados de teste.

dados_fit<- last_fit(final_rf, atraso_split)
dados_fit

```

# Resultados

```{r}

#Métricas para os dados de treino
resultado_dados_fit <-
  atraso_train %>%
  bind_cols(predict(dados_fit$.workflow[[1]], atraso_train) %>%
              rename(predicao_dados_fit= .pred))

print(metrics(resultado_dados_fit,
              truth = covid,
              estimate = predicao_dados_fit,
              options = "rmse"))

#Métricas para os dados de teste 
resultado_dados_fit <-
  atraso_test %>%
  bind_cols(predict(dados_fit$.workflow[[1]], atraso_test) %>%
              rename(predicao_dados_fit= .pred))


print(metrics(resultado_dados_fit,
              truth = covid,
              estimate = predicao_dados_fit,
              options = "rmse"))


modelo <- predict(dados_fit$.workflow[[1]],atraso_train) %>% 
  mutate(dias= 1:(639))
atraso <- atraso_train %>% 
  mutate(dias= 1:(639))

geral <- full_join(modelo, atraso, by = 'dias') %>% 
         mutate(date=(date('2020-03-04'):date('2021-12-02')))

geral$date <- as_date(geral$date)

ggplot(geral, aes(covid, .pred))+
  geom_abline(lty = 2, color = "gray50") +
  geom_point(alpha = 0.5, color = "midnightblue")+
  labs(title="Relação entre o número de casos e os valores preditos",
       y="Predição", x="Número de casos")+
  theme_minimal()

ggplot(geral)+
  geom_line(aes(x = date, y = covid, color = "Observado"))+
  geom_line(aes(x = date, y = .pred, color = "Predito"))+
  scale_colour_manual(values = c("midnightblue", "yellow"))+
  scale_x_date(date_breaks = "4 month", labels=date_format("%b %y"))+
  labs(title= "Predição para os dados de treino",
       y="Número de casos",
       x="Data",
       colour="legenda")+
  theme_minimal()

modelo_k <- predict(dados_fit$.workflow[[1]], atraso_test) %>% 
  mutate(dias= 1:7)
atraso_k<- atraso_test %>% 
  mutate(dias= 1:7)


geral_teste <- full_join(modelo_k, atraso_k, by = 'dias') %>% 
         mutate(date=(date('2021-12-03'):date('2021-12-09')))

geral_teste$date <- as_date(geral_teste$date)

ggplot(geral_teste)+
  geom_line(aes(x = date, y = covid, color = "Observado"))+
  geom_line(aes(x = date, y = .pred, color = "Predito"))+
  scale_colour_manual(values = c("midnightblue", "yellow"))+
  scale_x_date(date_breaks = "2 day", labels=date_format("%d %b %y"))+
  labs(title= "Predição para os dados de teste",
       y="Número de casos",
       x="Data",
       colour="legenda")+
  theme_minimal()

  
```

